### PR TITLE
Remove delegate to localhost

### PR DESCRIPTION
**Pull request by megalithSE**
We run AWX(ansible tower) in docker containers. We would like to skip re-image the contianer for every linux package dependency like in this case Ovftool from VMware. To make this possible I have to use 'delegate_to' on the whole role. And this pull request removes the use of 'delegate_to: localhost' on all sub-tasks. 
I did a run using the role from my Github branch after I removed this and it works like a charm!
Here is the task I run with some requirements:
```
  tasks:
    - name: Requirements for AVI
      pip:
        name:
          - avisdk
          - pyvmomi
          - requests_toolbelt
      become: true
      delegate_to: serverX.company.com
    
    - name: Deploy SE on VC
      import_role:
        name: avinetworks.avise_vmware
      vars:
        se_master_ctl_ip: "{{ avi_credentials.controller }}"
        se_master_ctl_username: "{{ avi_credentials.username }}"
        se_master_ctl_password: "{{ avi_credentials.password }}"
        se_cloud_name: NoAccess
        se_tenant: "{{ avi_tenant }}"
        se_group_name: "{{ avi_se_grp_name }}"
        ovftool_path: "{{ ovftool_run_path | default('/usr/bin/') }}"
        vcenter_host: "{{ vcsa_hostname }}"
        vcenter_user: "{{ vcsa_username }}"
        vcenter_password: "{{ vcsa_password }}"
        se_vmw_datacenter: "{{ vcsa_datacenter }}"
        se_vmw_cluster: "{{ vcsa_cluster }}"
        se_vmw_ovf_networks:
          'Management': Avi-SE-mgmt
          'Data Network 1': Avi-SE-Ext-Link
          'Data Network 2': Avi-SE-Int-Link
          'Data Network 3': Avi-SE-dmz
          'Data Network 4': Avi Internal
          'Data Network 5': Avi Internal
          'Data Network 6': Avi Internal
          'Data Network 7': Avi Internal
          'Data Network 8': Avi Internal
          'Data Network 9': Avi Internal
        se_vmw_vm_name: "{{ vcsa_vm_name }}"
        se_vmw_power_on: true
        se_vmw_vcenter_folder: infrastructure
        se_vmw_number_of_cpus: 2
        se_vmw_memory: 8192
        se_vmw_disk_size: 60
        se_vmw_mgmt_ip: "{{ se_mgmt_ip }}"
        se_vmw_mgmt_mask: 255.255.255.0
        se_vmw_default_gw: 10.0.0.1
        se_vmw_ovf_properties: 
          'avi.DNS.SE': "SERVERS:1.1.1.1,8.8.8.8"
      delegate_to: serverX.company.com
```

### CODE REVIEW

**Comment by megalithSE** [comment]
If you want more information about how we run this just let me know.

**Comment by shubhamavi** [comment]
@megalithSE is it required when you run the playbook from one machine and you have avitools/sdk dependencies installed in some other machine/container

**Comment by megalithSE** [comment]
> @megalithSE is it required when you run the playbook from one machine and you have avitools/sdk dependencies installed in some other machine/container

The first task in my post is so the remote machine also will have avisdk on it. We currently have a setup where the remote(delegated) machine is a docker container. And we just mount ova_file path and have a docker image with ovftool in it.

**Comment by manojkumarjain** [comment]
To remove hard dependency to  localhost  for SDK and avitools is good idea.
But can we make it as default option and override it if required.

This feature may be useful when we are integrating our roles with other external roles

**Comment by megalithSE** [comment]
Taken from _Ansible Configuration Management - Second Edition_ : 

> Ansible, by default, runs its tasks all at once on the configured machine.

So I don't see why you should have it in the first place.
But if you do a variable so we can change it I guess that will work fine.

**Comment by shubhamavi** [comment]
@megalithSE The `delegate_to: localhost` was introduced assuming that the controller machine does not have the andible-avisdk dependency and in that case we would not want to run those specific tasks on the controller.
Removing `delegate_to: localhost` makes ansible run the sdk dependent tasks on the controller, resulting in a failure. It is also important to keep controller in the hosts file to run controller specific tasks (like checking if the ova image is generated/present on the controller or not).
I'm currently working on a generic fix that takes care of both our scenarios, need to test that on tower and then we can update it.

**Pull request closed without merging**
